# Generated by Django 4.1.4 on 2022-12-20 19:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='file',
            field=models.FileField(upload_to='', verbose_name=django.core.files.storage.FileSystemStorage(location='/static')),
        ),
    ]
