# Generated by Django 4.1.4 on 2022-12-20 19:43

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_predict_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/static/'), upload_to=''),
        ),
    ]
